### ISSUE TITLE
readme requirements

### ISSUE THREAD

**Issue by inordeck** [cg923/trans-friendly#3]
your readme file is great. love the background and explanation of what the app is for. one thing to get you above the requirements is to include all the required links.
- heroku link
- trello link
- links to documentation for api's used
- link to prototype, if you have it.

**Comment by cg923** [comment]
Thanks Ian!  I totally missed that stuff.  I added a link to my Heroku project, my Trello board, and the API's I used.  My completely broken and unworkable prototype is not worth linking to ;)
