### ISSUE TITLE
Elements crowding each other at smaller screen sizes, especially my long username

### ISSUE THREAD

**Issue by jeffDevelops** [cg923/trans-friendly#4]
Hey, again! :)

Again, great job!

One maybe simple fix: my email address is very, very long, and when I collapsed the browser window, the logged-in display you made crowds the other elements on the page, similar to that German-words-are-really-long design phenomenon we talked about. Some other elements seems to be crowding others at smaller screen sizes, also.

**Comment by cg923** [comment]
Thanks Jeff!

This was super helpful.  I knew the page needed to be more responsive, but the extra long e-mail made things REALLY weird.  It's definitely still not perfect, but nothing is overlapping anything anymore.  In other words, it doesn't look perfect, but everything is totally usable on mobile!
